2020-03-22 14:24:15,207 - [food_bill.py:21 - get_user_credentials() ] - WARNING - Getting user inputs
2020-03-22 14:24:23,635 - [food_bill.py:34 -             <module>() ] - INFO - User is valid...
2020-03-22 14:24:23,635 - [food_bill.py:7 - show_billing_options() ] - WARNING - Here is your hotel menu, Enjoy your meal ....
2020-03-22 14:24:23,635 - [food_bill.py:9 - show_billing_options() ] - DEBUG - pepsi : 40
2020-03-22 14:24:23,635 - [food_bill.py:9 - show_billing_options() ] - DEBUG - idly : 20
2020-03-22 14:52:38,307 - [food_bill_with_logger.py:21 - get_user_credentials() ] - WARNING - Getting user inputs
2020-03-22 14:52:43,854 - [food_bill_with_logger.py:16 -        validate_user() ] - WARNING - Entered Invalid User and Password...
2020-03-22 14:52:43,854 - [food_bill_with_logger.py:38 -             <module>() ] - WARNING - User not found, Try again ...
2020-03-28 18:50:17,124 - [food_bill_with_logger.py:21 - get_user_credentials() ] - WARNING - Getting user inputs
2020-03-28 18:50:23,105 - [food_bill_with_logger.py:16 -        validate_user() ] - WARNING - Entered Invalid User and Password...
2020-03-28 18:50:23,105 - [food_bill_with_logger.py:37 -                first() ] - WARNING - User not found, Try again ...
2020-03-28 18:50:23,105 - [food_bill_with_logger.py:21 - get_user_credentials() ] - WARNING - Getting user inputs
2020-03-28 18:50:25,400 - [food_bill_with_logger.py:16 -        validate_user() ] - WARNING - Entered Invalid User and Password...
2020-03-28 18:50:25,400 - [food_bill_with_logger.py:37 -                first() ] - WARNING - User not found, Try again ...
2020-03-28 18:50:25,400 - [food_bill_with_logger.py:21 - get_user_credentials() ] - WARNING - Getting user inputs
2020-03-28 18:50:27,293 - [food_bill_with_logger.py:16 -        validate_user() ] - WARNING - Entered Invalid User and Password...
2020-03-28 18:50:27,293 - [food_bill_with_logger.py:41 -                first() ] - ERROR - You have exceeded the maximum 3 number of attempts.....Exiting.......
